package com.ucweb.common.util.p;

/* compiled from: ProGuard */
public final class b {
    public static final String A;
    public static final String B;
    public static final String C;
    public static final String D;
    public static final String E;
    public static final String F;
    public static final String G;
    public static final String H;
    public static final String I;
    public static final String J;
    public static final String K;
    public static final String L;
    public static final String M;
    public static final String N;
    public static final String O;
    public static final String P;
    private static int Q;
    public static final String a;
    public static final String b;
    public static final String c;
    public static final String d;
    public static final String e;
    public static final String f;
    public static final String g;
    public static final String h;
    public static final String i;
    public static final String j;
    public static final String k;
    public static final String l;
    public static final String m;
    public static final String n;
    public static final String o;
    public static final String p;
    public static final String q;
    public static final String r;
    public static final String s;
    public static final String t;
    public static final String u;
    public static final String v;
    public static final String w;
    public static final String x;
    public static final String y;
    public static final String z;

    static {
        Q = 0;
        StringBuilder stringBuilder = new StringBuilder("uk");
        int i = Q;
        Q = i + 1;
        a = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        b = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        c = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        d = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        e = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        f = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        g = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        h = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        i = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        j = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        k = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        l = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        m = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        n = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        o = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        p = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        q = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        r = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        s = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        t = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        u = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        v = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        w = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        x = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        y = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        z = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        A = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        B = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        C = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        D = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        E = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        F = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        G = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        H = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        I = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        J = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        K = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        L = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        M = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        N = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        O = stringBuilder.append(i).toString();
        stringBuilder = new StringBuilder("uk");
        i = Q;
        Q = i + 1;
        P = stringBuilder.append(i).toString();
    }
}
