package com.uc.webview.browser.interfaces;

import android.graphics.drawable.Drawable;
import com.uc.webview.export.annotations.Interface;
import com.uc.webview.export.internal.interfaces.IWebResourceInternal;

@Deprecated
@Interface
/* compiled from: ProGuard */
public interface IWebResources extends IWebResourceInternal {
    public static final String[] BITMAP_RESOURCES = new String[]{TEXT_FLSASH_APP_DISABLED, TEXT_FLASH_APP_NOT_ISNTALLED, TEXT_FLASH_DATA_LOADING, TEXT_FLASH_DATA_VALID, "plugin_waitfor_load", "plugin_app_disabled", "plugin_app_not_installed", "flash_app_downloading_btn", TEXT_PLUGIN_APP_DOWNLOADING, "pic_none", "pic_fail", "pic_loading", "pic_none_hint", "radio_normal", "radio_selected", "check_normal", "check_selected", DRAWABLE_INPUT_RANGE_SLIDER_THUMB, "media_btn_play", "media_btn_pause", "media_btn_forward", "media_btn_back", "media_slider_left", "media_slider_right", "media_slider_middle", "media_slider_cursor", "media_slider_passed", "media_normalscreen_play_normal", "core_upload_control_photo", "core_upload_control_pic", "core_upload_control_file", "core_speech_input_button", "core_speech_input_button_focused", "ac_progress_blue", "ac_pause_normal", "ac_play_normal", "ic_media_rew", "ic_media_ff", "ac_enter_fullscreen_normal", "ac_download_normal", "ac_underplay", "ac_underpause", "spinner_76_outer_holo", "spinner_76_inner_holo", "ic_media_video_poster", "media_controller_bg_bottom", "ac_progress_bg", "ac_progress_slider", DRAWABLE_FREECOPY_UPWARD_BG_LEFT, DRAWABLE_FREECOPY_UPWARD_BG_MIDDLE, DRAWABLE_FREECOPY_UPWARD_BG_RIGHT, DRAWABLE_FREECOPY_DOWNWARD_BG_LEFT, DRAWABLE_FREECOPY_DOWNWARD_BG_MIDDLE, DRAWABLE_FREECOPY_DOWNWARD_BG_RIGHT, IWebResourceInternal.DRAWABLE_UC_LOGO, IWebResourceInternal.DRAWABLE_WEBVIEW_DROP_DOWN_SHADOW};
    public static final String COLOR_CONTENT_EDITABLE_TEXT_SEL_BG = "contentEditableTextSelBg";
    public static final String COLOR_CONTENT_EDITABLE_TEXT_SEL_FG = "contentEditableTextSelFg";
    public static final String COLOR_FOCUS_FRAME_BORDER = "focusFrameBorder";
    public static final String COLOR_FOCUS_FRAME_BORDER_GREY = "focusFrameBorderGrey";
    public static final String COLOR_FOCUS_FRAME_FILLED = "focusFrameFilled";
    public static final String COLOR_FOCUS_FRAME_FILLED_GREY = "focusFrameFilledGrey";
    public static final String COLOR_FREECOPYMENU_DIVIDER = "freecopymenu_dividercolor";
    public static final String COLOR_FREECOPYMENU_FOCUSDOWN = "freecopymenu_focusdowncolor";
    public static final String COLOR_FREECOPYMENU_FOCUSUP = "freecopymenu_focusupcolor";
    public static final String COLOR_FREECOPYMENU_TEXT = "freecopymenu_textcolor";
    public static final String COLOR_SCROLLBAR_BG = "scrollbarBg";
    public static final String COLOR_SCROLLBAR_THUMB = "scrollbarThumb";
    public static final String COLOR_TEXT_SEARCH_BORDER = "textSearchBorder";
    public static final String COLOR_TEXT_SEARCH_FILLED = "textSearchFilled";
    public static final String COLOR_TEXT_SELECTION_BG = "textSelectionBg";
    public static final String COLOR_TEXT_SELECTION_CARET_END = "textSelectionCaretEnd";
    public static final String COLOR_TEXT_SELECTION_CARET_SHADOW_END = "textSelectionCaretShadowEnd";
    public static final String COLOR_TEXT_SELECTION_CARET_SHADOW_START = "textSelectionCaretShadowStart";
    public static final String COLOR_TEXT_SELECTION_CARET_START = "textSelectionCaretStart";
    public static final String COLOR_TEXT_SELECTION_FG = "textSelectionFg";
    public static final String COLOR_WEB_VIEW_BG = "webviewBg";
    public static final String DIR_THIRD_PARTY_CODE = "dir_third_party_code";
    public static final String DRAWABLE_BTN_BG_CAMERA_CANCEL = "btn_bg_camera_cancel";
    public static final String DRAWABLE_BTN_BG_CAMERA_CAPTURE = "btn_bg_camera_capture";
    public static final String DRAWABLE_BTN_BG_CAMERA_CONFIRM = "btn_bg_camera_confirm";
    public static final String DRAWABLE_CALL_MASTER = "call_master";
    public static final String DRAWABLE_DEFAULT_VIDEO_POSTER = "default_video_poster";
    public static final String DRAWABLE_DIVIDER_HORIZONTAL_BRIGHT = "divider_horizontal_bright";
    public static final String DRAWABLE_FAST_SCROLL_THUMB_DAY = "fast_scroll_thumb_day";
    public static final String DRAWABLE_FAST_SCROLL_THUMB_NIGHT = "fast_scroll_thumb_night";
    public static final String DRAWABLE_FREECOPY_BACKGROUND = "freemenu_background_9";
    public static final String DRAWABLE_FREECOPY_DOWN = "freecopy_down";
    public static final String DRAWABLE_FREECOPY_DOWNWARD_BG_LEFT = "freemenu_downward_bg_left_9";
    public static final String DRAWABLE_FREECOPY_DOWNWARD_BG_MIDDLE = "freemenu_downward_bg_middle_9";
    public static final String DRAWABLE_FREECOPY_DOWNWARD_BG_RIGHT = "freemenu_downward_bg_right_9";
    public static final String DRAWABLE_FREECOPY_UPWARD_BG_LEFT = "freemenu_upward_bg_left_9";
    public static final String DRAWABLE_FREECOPY_UPWARD_BG_MIDDLE = "freemenu_upward_bg_middle_9";
    public static final String DRAWABLE_FREECOPY_UPWARD_BG_RIGHT = "freemenu_upward_bg_right_9";
    public static final String DRAWABLE_INPUT_RANGE_SLIDER_THUMB = "input_range_slider_thumb";
    public static final String DRAWABLE_MEIDA_CLOSE = "media_close";
    public static final String DRAWABLE_MENU_SUBMENU_BACKGROUND = "menu_submenu_background_9";
    public static final String DRAWABLE_PAGE_SCROLLBAR = "page_scrollbar";
    public static final String DRAWABLE_POPUP_ZOOMER_FRAME = "ondemand_overlay_9";
    public static final String DRAWABLE_RESOLUTION_ITEM_BG_NORMAL = "resolution_item_bg_normal";
    public static final String DRAWABLE_RESOLUTION_ITEM_BG_PRESS = "resolution_item_bg_press";
    public static final String DRAWABLE_SCROLLBAR_HANDLE_ACCELERATED_ANIM2 = "scrollbar_drag";
    public static final String DRAWABLE_TEXT_SELECTION_HANDLE = "text_selection_handle";
    public static final String DRAWABLE_TEXT_SELECTION_HANDLE_NIGHT = "text_selection_handle_night";
    public static final String DRAWABLE_TEXT_SELECTION_LEFT_HANDLE = "freecopy_border_left";
    public static final String DRAWABLE_TEXT_SELECTION_LEFT_NARROW_HANDLE = "text_selection_left_narrow";
    public static final String DRAWABLE_TEXT_SELECTION_LEFT_NARROW_HANDLE_NIGHT = "ext_selection_left_narrow_night";
    public static final String DRAWABLE_TEXT_SELECTION_LOCATOR = "freecopy_border_below";
    public static final String DRAWABLE_TEXT_SELECTION_MAGNIFIER = "magnifier";
    public static final String DRAWABLE_TEXT_SELECTION_MAGNIFIER_MASK = "magnifier_mask";
    public static final String DRAWABLE_TEXT_SELECTION_RIGHT_HANDLE = "freecopy_border_right";
    public static final String DRAWABLE_TEXT_SELECTION_RIGHT_NARROW_HANDLE = "text_selection_right_narrow";
    public static final String DRAWABLE_TEXT_SELECTION_RIGHT_NARROW_HANDLE_NIGHT = "text_selection_right_narrow_night";
    public static final int INVALID_RESOURCE_ID = -1;
    public static final String[] LANGUAGE_RELATED_BITMAP_RESOURCES = new String[]{"ucplugin_icon", "ucplugin_app_not_installed"};
    public static final String MEDIA_ENTERFULL_BUTTON = "media_enterfull_button_normal";
    public static final String MEDIA_EXITFULL_BUTTON = "media_exitfull_button_normal";
    public static final String MEDIA_LOADING = "video_loading";
    public static final String MEDIA_PAUSE_BUTTON = "media_fullscreen_pause_button_normal";
    public static final String MEDIA_PLAY_BUTTON = "media_fullscreen_play_button_normal";
    public static final String PICTURE_VIEWER_BUTTON_PRESSED = "picture_viewer_button_pressed";
    public static final String PICTURE_VIEWER_IMAGE_LOADING = "image_loading";
    public static final String PICTURE_VIEWER_RETURN_ICON = "picture_viewer_return_icon";
    public static final String PICTURE_VIEWER_TITLE_BAR_BG = "picture_viewer_titlebarbg_9";
    public static final String RESOURCEID_ARD_INTER_R_DRAWABLE_BTN_CHECK_OFF = "com.android.internal.R$drawable.btn_check_off";
    public static final String RESOURCEID_ARD_INTER_R_RAW_LOADERROR = "com.android.internal.R$raw.loaderror";
    public static final String RESOURCEID_ARD_INTER_R_RAW_NODOMAIN = "com.android.internal.R$raw.nodomain";
    public static final String RESOURCEID_ATTR_WEBVIEWSTYLE = "com.android.internal.R$attr.webViewStyle";
    public static final String RESOURCEID_ID_ZOOMCONTROLS = "com.android.internal.R$id.zoomControls";
    public static final String RESOURCEID_ID_ZOOMMAGNIFY = "com.android.internal.R$id.zoomMagnify";
    public static final String RESOURCEID_LAYOUT_ID_MESSAGE = "com.android.internal.R$id.message";
    public static final String RESOURCEID_LAYOUT_ID_VALUE = "com.android.internal.R$id.value";
    public static final String RESOURCEID_LAYOUT_JS_PROMPT = "com.android.internal.R$layout.js_prompt";
    public static final String RESOURCEID_LAYOUT_SELECT_DIALOG = "com.android.internal.R$layout.select_dialog";
    public static final String RESOURCEID_LAYOUT_SELECT_DIALOG_MULTICHOICE = "com.android.internal.R$layout.select_dialog_multichoice";
    public static final String RESOURCEID_LAYOUT_SELECT_DIALOG_SINGLECHOICE = "com.android.internal.R$layout.select_dialog_singlechoice";
    public static final String RESOURCEID_LAYOUT_ZOOM_MAGNIFY = "com.android.internal.R$layout.zoom_magnify";
    public static final String RESOURCEID_NOTIFICATION_ICON = "com.android.internal.R$drawable.stat_notify_more";
    public static final String RESOURCEID_PLURALS_LAST_NUM_DAYS = "com.android.internal.R$plurals.last_num_days";
    public static final String RESOURCEID_STRING_CANCEL = "com.android.internal.R$string.cancel";
    public static final String RESOURCEID_STRING_HTTPERROR = "com.android.internal.R$string.httpError";
    public static final String RESOURCEID_STRING_HTTPERRORBADURL = "com.android.internal.R$string.httpErrorBadUrl";
    public static final String RESOURCEID_STRING_HTTPERRORFILENOTFOUND = "com.android.internal.R$string.httpErrorFileNotFound";
    public static final String RESOURCEID_STRING_HTTPERRORREDIRECTLOOP = "com.android.internal.R$string.httpErrorRedirectLoop";
    public static final String RESOURCEID_STRING_HTTPERRORTOOMANYREQUESTS = "com.android.internal.R$string.httpErrorTooManyRequests";
    public static final String RESOURCEID_STRING_HTTPERRORUNSUPPORTEDSCHEME = "com.android.internal.R$string.httpErrorUnsupportedScheme";
    public static final String RESOURCEID_STRING_JS_DIALOG_BEFORE_UNLOAD = "com.android.internal.R$string.js_dialog_before_unload";
    public static final String RESOURCEID_STRING_JS_DIALOG_TITLE = "com.android.internal.R$string.js_dialog_title";
    public static final String RESOURCEID_STRING_JS_DIALOG_TITLE_DEFAULT = "com.android.internal.R$string.js_dialog_title_default";
    public static final String RESOURCEID_STRING_LAST_MONTH = "com.android.internal.R$string.last_month";
    public static final String RESOURCEID_STRING_OK = "com.android.internal.R$string.ok";
    public static final String RESOURCEID_STRING_OLDER = "com.android.internal.R$string.older";
    public static final String RESOURCEID_STRING_OPEN_PERMISSION_DENY = "com.android.internal.R$string.open_permission_deny";
    public static final String RESOURCEID_STRING_RESET = "com.android.internal.R$string.reset";
    public static final String RESOURCEID_STRING_SAVE_PASSWORD_LABEL = "com.android.internal.R$string.save_password_label";
    public static final String RESOURCEID_STRING_SAVE_PASSWORD_MESSAGE = "com.android.internal.R$string.save_password_message";
    public static final String RESOURCEID_STRING_SAVE_PASSWORD_NEVER = "com.android.internal.R$string.save_password_never";
    public static final String RESOURCEID_STRING_SAVE_PASSWORD_NOTNOW = "com.android.internal.R$string.save_password_notnow";
    public static final String RESOURCEID_STRING_SAVE_PASSWORD_REMEMBER = "com.android.internal.R$string.save_password_remember";
    public static final String RESOURCEID_STRING_SUBMIT = "com.android.internal.R$string.submit";
    public static final String RESOURCEID_STRING_TEXT_COPIED = "com.android.internal.R$string.text_copied";
    public static final String RESOURCEID_STRING_TODAY = "com.android.internal.R$string.today";
    public static final String RESOURCEID_STRING_UPLOAD_FILE = "com.android.internal.R$string.upload_file";
    public static final String RESOURCEID_STRING_VIDEOVIEW_ERROR_BUTTON = "com.android.internal.R$string.VideoView_error_button";
    public static final String RESOURCEID_STRING_VIDEOVIEW_ERROR_TEXT_INVALID_PROGRESSIVE_PLAYBACK = "com.android.internal.R$string.VideoView_error_text_invalid_progressive_playback";
    public static final String RESOURCEID_STRING_VIDEOVIEW_ERROR_TEXT_UNKNOWN = "com.android.internal.R$string.VideoView_error_text_unknown";
    public static final String RESOURCEID_STRING_WEBCORETHREAD_WATCHDOG_ALERT_TITLE = "com.android.internal.R$string.anr_process";
    public static final String RESOURCEID_STRING_WEBCORETHREAD_WATCHDOG_FORCE_CLOSE = "com.android.internal.R$string.force_close";
    public static final String RESOURCEID_STRING_WEBCORETHREAD_WATCHDOG_WAIT = "com.android.internal.R$string.wait";
    public static final String RESOURCEID_STRING_YESTERDAY = "com.android.internal.R$string.yesterday";
    public static final int RESOURCE_TYPE_BITMAP_PATH = 1;
    public static final int RESOURCE_TYPE_COLOR = 3;
    public static final int RESOURCE_TYPE_DRAWABLE = 2;
    public static final int RESOURCE_TYPE_RESOURCE_ID = 4;
    public static final int RESOURCE_TYPE_TEXT = 0;
    public static final int RESOURCE_TYPE_UNKOWN = -1;
    public static final String SEEKBAR_SCRUBBER_BACKGROUND = "seekbar_scrubber_background_9";
    public static final String SEEKBAR_SCRUBBER_CONTROL = "seekbar_scrubber_control_focused";
    public static final String SEEKBAR_SCRUBBER_PROGRESS = "seekbar_scrubber_progress_9";
    public static final String SEEKBAR_SCRUBBER_SECONDARY = "seekbar_scrubber_secondary_9";
    public static final String TEXT_BTN_DEFAULT_FILE_CHOOSE = "file_choose";
    public static final String TEXT_BTN_DEFAULT_FILE_NO_SELECTED = "file_no_selected";
    public static final String TEXT_BTN_DEFAULT_PHOTO_UPLOAD_FILE = "photo_upload_file";
    public static final String TEXT_BTN_DEFAULT_RESET = "reset";
    public static final String TEXT_BTN_DEFAULT_SUBMIT = "submit";
    public static final String TEXT_CANCEL = "text_cancel";
    public static final String TEXT_CANNOT_SUPPORT_FLASH_FILE = "cannotSupportFlashFile";
    public static final String TEXT_CLEAR = "text_clear";
    public static final String TEXT_COLOR_HUE = "color_hue";
    public static final String TEXT_COLOR_PICKER_DIALOG_TITLE = "color_picker_dialog_title";
    public static final String TEXT_COLOR_SATURATION = "color_saturation";
    public static final String TEXT_COLOR_VALUE = "color_value";
    public static final String TEXT_COPY = "copy";
    public static final String TEXT_CUT = "cut";
    public static final String TEXT_DATE_PICKER_DIALOG_TITLE = "date_picker_dialog_title";
    public static final String TEXT_DATE_TIME_PICKER_DIALOG_TITLE = "date_time_picker_dialog_title";
    public static final String TEXT_DEFAULT_DETAILS_SUMMARY_TEXT = "default_details_summary_text";
    public static final String TEXT_EXPAND_SELECTION = "expand_selection";
    public static final String TEXT_FLASH_APP_NOT_ISNTALLED = "flash_app_not_installed";
    public static final String TEXT_FLASH_DATA_LOADING = "flash_data_loading";
    public static final String TEXT_FLASH_DATA_LOADING_CANCLE = "flash_data_loading_cancle";
    public static final String TEXT_FLASH_DATA_LOAD_FAILED = "flash_data_load_failed";
    public static final String TEXT_FLASH_DATA_MISSING = "flash_data_missing";
    public static final String TEXT_FLASH_DATA_VALID = "flash_data_valid";
    public static final String TEXT_FLSASH_APP_DISABLED = "flash_app_disabled";
    public static final String TEXT_FULL_SELECTION = "text_full_selection";
    public static final String TEXT_MONTH_PICKER_DIALOG_TITLE = "month_picker_dialog_title";
    public static final String TEXT_MORE = "color_picker_button_more";
    public static final String TEXT_NOTIFICATION_PERMISSION_ALLOW = "permission_allow";
    public static final String TEXT_NOTIFICATION_PERMISSION_ALLOW_ONCE = "permission_allow_once";
    public static final String TEXT_NOTIFICATION_PERMISSION_DENY = "permission_deny";
    public static final String TEXT_NOTIFICATION_PERMISSION_MESSAGE = "permission_message";
    public static final String TEXT_OTHER = "other";
    public static final String TEXT_PASTE = "paste";
    public static final String TEXT_PICTURE_VIEWER_LOADING_INDICATION_TEXT = "picture_viewer_loading_indication_text";
    public static final String TEXT_PLUGIN_APP_DOWNLOADING = "plugin_app_downloading";
    public static final String TEXT_PLUGIN_APP_INSTALLING = "plugin_app_installing";
    public static final String TEXT_POST_REDIRECT_CONFIRM = "post_redirect_confirm";
    public static final String TEXT_PROMPT_MSG_DATA_ERROR = "prompt_msg_data_error";
    public static final String TEXT_PROMPT_MSG_ERROR_LOAD_FILE = "prompt_msg_error_load_file";
    public static final String TEXT_PROMPT_MSG_ERROR_LOAD_URL = "prompt_msg_error_load_url";
    public static final String TEXT_PROMPT_MSG_FAILED_TO_OPEN_FILE = "prompt_msg_failed_to_open_file";
    public static final String TEXT_PROMPT_MSG_FAILED_TO_READ_FILE = "prompt_msg_failed_to_read_file";
    public static final String TEXT_PROMPT_MSG_FILE_NOT_EXIST = "prompt_msg_file_not_exist";
    public static final String TEXT_PROMPT_MSG_MEMORY_ALLOC_FAILURE = "prompt_msg_memory_alloc_failure";
    public static final String TEXT_SEARCH = "search";
    public static final String TEXT_SELECTION = "text_selection";
    public static final String TEXT_SET = "text_set";
    public static final String TEXT_SHARE = "share";
    public static final String TEXT_SMARTREADER_CANCELED = "smartreader_canceled";
    public static final String TEXT_SMARTREADER_FAILED = "smartreader_failed";
    public static final String TEXT_SMARTREADER_HIDE_FOOTER = "smartreader_hide_footer";
    public static final String TEXT_SMARTREADER_LOADING = "smartreader_loading";
    public static final String TEXT_SMARTREADER_NOMORE_BOTTOM = "smartreader_nomore_bottom";
    public static final String TEXT_SMARTREADER_NOMORE_TOP = "smartreader_nomore_top";
    public static final String TEXT_SMARTREADER_SHOW_FOOTER = "smartreader_show_footer";
    public static final String TEXT_SPEECH_DELETE = "speech_delete";
    public static final String TEXT_TIME_PICKER_DIALOG_TITLE = "time_picker_dialog_title";
    public static final String TEXT_TIP_CAPTURE_FAIL = "tip_capture_fail";
    public static final String TEXT_TIP_CAPTURE_RESOLUTION = "tip_capture_resolution";
    public static final String TEXT_TIP_CAPTURE_SIZE = "tip_capture_size";
    public static final String TEXT_TIP_CAPTURE_UPLOAD = "tip_capture_upload";
    public static final String TEXT_UC_CALLMASTER_USE_APP = "uc_callmaster_use_app";
    public static final String TEXT_UPLOAD_CONTROL_DELETE = "upload_control_delete";
    public static final String TEXT_UPLOAD_CONTROL_FILE = "upload_control_file";
    public static final String TEXT_UPLOAD_CONTROL_PHOTO = "upload_control_photo";
    public static final String TEXT_UPLOAD_CONTROL_PIC = "upload_control_pic";
    public static final String TEXT_VALIDATION_MESSAGE_MISSING_SELECT = "validation_message_missing_select";
    public static final String TEXT_VALIDATION_MESSAGE_MISSING_TEST = "validation_message_missing_text";
    public static final String TEXT_VALIDATION_MESSAGE_PATTERN_MISMATCH = "validation_message_pattern_mismatch";
    public static final String TEXT_VALIDATION_MESSAGE_RANGE_OVERFLOW = "validation_message_range_overflow";
    public static final String TEXT_VALIDATION_MESSAGE_RANGE_UNDERFLOW = "validation_message_range_underflow";
    public static final String TEXT_VALIDATION_MESSAGE_TOO_LONG = "validation_message_too_long";
    public static final String TEXT_VALIDATION_MESSAGE_TYPE_MISMATCH_EMAIL = "validation_message_type_mismatch_email";
    public static final String TEXT_VALIDATION_MESSAGE_TYPE_MISMATCH_MULTIPLE_EMAIL = "validation_message_type_mismatch_multiple_email";
    public static final String TEXT_VALIDATION_MESSAGE_TYPE_MISMATCH_URL = "validation_message_type_mismatch_url";
    public static final String TEXT_WEEK_PICKER_DIALOG_TITLE = "week_picker_dialog_title";
    public static final String VIDEO_GUIT_BRIGHTNESS_VIEW = "player_hint_area_brightness";
    public static final String VIDEO_GUIT_FAST_BACKWARD_VIEW = "player_hint_area_rew";
    public static final String VIDEO_GUIT_FAST_FORWARD_VIEW = "player_hint_area_ff";
    public static final String VIDEO_GUIT_FRESHER_GUIDE = "media_controller_fresher_guide";
    public static final String VIDEO_GUIT_VOLUME_VIEW = "player_hint_area_volume";
    public static final String VIDEO_TOP_BAR_BACK = "player_top_back";
    public static final String VIDEO_TOP_BAR_BACKGROUND = "top_bar_background";
    public static final String VIDEO_TOP_BAR_BACK_DIVIDER = "player_top_back_divider";
    public static final String VIDEO_TOP_BATTERU_CHARGING_CONTENT = "player_battery_charging_content";
    public static final String VIDEO_TOP_NET_TYPE_LOCAL = "video_net_type_local";
    public static final String VIDEO_TOP_NET_TYPE_MOBILE = "video_net_type_mobile";
    public static final String VIDEO_TOP_NET_TYPE_WIFI = "video_net_type_wifi";

    String getBitmapPath(String str);

    int getColor(String str);

    Drawable getDrawable(String str);

    int getResourceId(String str);

    String getText(String str);

    void onResourcesChanged(int i);

    void setBitmapPath(String str, String str2);

    void setColor(String str, int i);

    void setResourceId(String str, int i);

    void setText(String str, int i);

    void setText(String str, String str2);
}
